sudo: false
language: c
blocklist:
    - *-pdf

env:
    global:
        - THEANO_FLAGS=floatX=float64,compute_test_value=off

matrix:
    include:
        - os: linux
          env: TEST_LANG='paper' PYTHON_VERSION=3.7 NUMPY_VERSION=latest

        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.15

        - os: linux
          env: PYTHON_VERSION=3.7 NUMPY_VERSION=1.16

        - os: osx
          env: PYTHON_VERSION=3.7 NUMPY_VERSION=1.16

cache:
    directories:
        - $HOME/miniconda
        - $HOME/.cache/Tectonic


install: |
    source .ci/travis.sh
    conda env export
    python -c 'import theano; print(theano.__version__)'
    python -c 'import celerite; print(celerite.__version__)'
    theano-cache purge
    python setup.py develop

script: |
    if [[ $TEST_LANG == 'paper' ]]
    then
      source .ci/build-paper.sh
    else
      py.test -v -s exoplanet
    fi

after_success: |
    if [[ $TEST_LANG -ne 'paper' ]]
    then
      coveralls
    fi
