sudo: false
language: c

env:
    global:
        - THEANO_FLAGS=floatX=float64,compute_test_value=off

matrix:
    include:
        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.15

        - os: linux
          env: PYTHON_VERSION=3.7 NUMPY_VERSION=1.16

        - os: osx
          env: PYTHON_VERSION=3.7 NUMPY_VERSION=1.16

install:
    - source .ci/travis.sh
    - conda env export
    - python -c 'import theano; print(theano.__version__)'
    - python -c 'import celerite; print(celerite.__version__)'
    - theano-cache purge
    - python setup.py develop

#cache:
#    directories:
#        - $HOME/miniconda

script:
    - py.test -v -s exoplanet

after_success:
    - coveralls
