pool:
  vmImage: Ubuntu-16.04

steps:

- script: |
    git submodule update --init
  displayName: 'Submodules'

- script: |
    sudo chown -R $USER $CONDA
    . $CONDA/etc/profile.d/conda.sh
    conda create --yes --quiet --name test python=3.7
  displayName: 'Setup conda'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda activate test
    pip install numpy pybind11
    pip install -r requirements-dev.txt
    conda install -q tectonic
  displayName: 'Install dependencies'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda activate test
    theano-cache purge
  displayName: 'Purging Theano cache'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda activate test
    cd paper
    make
  displayName: 'Building paper'
