#trigger:
#- master

strategy:
  matrix:
    LinuxPython36:
      imageName: 'Ubuntu-16.04'
      python.version: '3.6'
    LinuxPython37:
      imageName: 'Ubuntu-16.04'
      python.version: '3.7'
    MacPython36:
      imageName: 'macos-10.13'
      python.version: '3.6'
    MacPython37:
      imageName: 'macos-10.13'
      python.version: '3.7'

pool:
  vmImage: $(imageName)

steps:

- script: |
    git submodule update --init
  displayName: 'Submodules'

- script: |
    sudo chown -R $USER $CONDA
    . $CONDA/etc/profile.d/conda.sh
    conda create --yes --quiet --name test python=$(python.version)
  displayName: 'Setup conda'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda activate test
    conda install -c conda-forge --yes --quiet --name test numpy scipy pybind11
    pip install -r requirements-dev.txt
  displayName: 'Install dependencies'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda activate test
    theano-cache purge
  displayName: 'Purging Theano cache'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda activate test
    python debug.py
    py.test -v -s exoplanet
  displayName: 'Testing'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda activate test
    coveralls
  displayName: 'Coveralls'
