#trigger:
#- master

pool:
  vmImage: 'Ubuntu-16.04'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:

- script: |
    git submodule update --init
  displayName: 'Submodules'

- script: |
    sudo chown -R $USER $CONDA
    . $CONDA/etc/profile.d/conda.sh
  displayName: 'Add conda to PATH'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda create --yes --quiet --name test python=$(python.version)
  displayName: 'Create Anaconda environment'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda activate test
    conda install -c conda-forge --yes --quiet --name test numpy scipy starry celerite
    pip install -r requirements-dev.txt
  displayName: 'Install dependencies'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda activate test
    theano-cache purge
  displayName: 'Purging Theano cache'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda activate test
    python exoplanet/gp/celerite_test.py
  displayName: 'Testing'

#- script: |
#    . $CONDA/etc/profile.d/conda.sh
#    conda activate test
#    pip install pytest-azurepipelines
#    py.test -v -s exoplanet
#  displayName: 'Testing'
