# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
strategy:
  matrix:
    Python27:
      python.version: '2.7'
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:

- bash: |
    echo "##vso[task.prependpath]$CONDA/bin"
    sudo chown -R $USER /usr/share/miniconda
  displayName: 'Add conda to PATH'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    conda create --yes --quiet --name test python=$(python.version)
    conda install -c conda-forge --yes --quiet --name test numpy scipy starry
  displayName: 'Create Anaconda environment'

- script: |
    conda activate test
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install -r requirements-dev.txt
  displayName: 'Install dependencies'

- script: |
    conda activate test
    theano-cache purge
  displayName: 'Purging Theano cache'

- script: |
    conda activate test
    pip install pytest-azurepipelines
    py.test -v -s exoplanet
  displayName: 'Testing'
