[tool.black]
line-length = 79
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
known_third_party = ["astropy", "exoplanet_version", "matplotlib", "nbconvert", "nbformat", "numpy", "packaging", "pkg_resources", "pymc3", "pytest", "scipy", "setuptools", "sphinx_typlog_theme", "starry", "theano", "tqdm"]
