name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  tests:
    name: "${{ matrix.pymc-version }} on py${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        pymc-version: ["pymc3~=3.9", "pymc3~=3.10", "pymc3~=3.11"]
        include:
          - python-version: "3.9"
            pymc-version: "https://github.com/pymc-devs/pymc3/archive/master.zip"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/cache@v2
        with:
          path: ~/.theano
          key: xo-${{ runner.os }}-py${{ matrix.python-version }}-${{ matrix.pymc-version }}-${{ github.sha }}
          restore-keys: |
            xo-${{ runner.os }}-py${{ matrix.python-version }}-${{ matrix.pymc-version }}-

      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      # Setup
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install "${{ matrix.pymc-version }}"
          python -m pip install -e .[test]
          python -m pip install --no-deps starry rebound-pymc3

      - name: Run tests
        shell: bash -l {0}
        run: python -m pytest --cov=exoplanet -v tests

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel: true
          flag-name: Unit Tests

  coverage:
    name: "Merge and upload coverage"
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel-finished: true
